[
    {
      "id": 101,
      "name": "Bone Marrow/Stem Cell",
      "review": 4.7,
      "price": 12550,
      "bannerImg": "https://i.ibb.co/MPbk0C0/bonmerrow-Banner.jpg",
      "image": "https://i.ibb.co/vwTpZV4/bonemerrow.jpg",
      "description": "Since 1968, our team has led the way in developing new techniques in bone marrow and stem cell transplants.",
      "longDescription": "What is a stem cell transplant? Doctors sometimes use the terms  bone marrow transplant  and  stem cell transplant interchangeably. That`s because they are two ways to describe the treatment hematopoietic cell transplant. If you need a transplant to treat blood or bone marrow cancer, your treatment will involve stem cells. Those stem cells may come from-    >>Your own bone marrow  >>Bone marrow from a donor  >>Your own blood >Blood from a donor  >>Blood from a donated umbilical cord.  The type of transplant your provider uses depends on the type of cancer you have and where we can find the best source of a good match.",
      "conditions": "Conditions we treat   >>Bone marrow transplants help to generate new healthy cells and eliminate cancer. You may be a candidate for a bone marrow transplant if you have-  >>Aplastic anemia- A rare condition where your body stops producing healthy blood cells.  >>Bone marrow disorders (hematologic malignancy)- Conditions that lead to problems with how stem cells develop.  >>Leukemia- A blood cancer caused by having too many white blood cells. >>Lymphoma- Cancer that begins in the immune cells that fight infections, called lymphocytes.  >>Multiple myeloma- Cancer that forms in your plasma cells, or white blood cells in the bone marrow.  >>Sickle cell disease- A group of disorders that causes your red blood cells to break down. ",
      "team": "Meet our team- Our team includes physicians and nurse practitioners who provide personalized care. We work closely with you before, during and after your transplant so you know exactly what to expect at each stage in your treatment journey."
      
    },
    {
      "id": 102,
      "name": "Kidney Transplant",
      "review": 4.8,
      "price": 19150,
      "bannerImg": "https://i.ibb.co/2WPT3V0/kidney-Banner.jpg",
      "image": "https://i.ibb.co/5KvPq44/kidney.jpg",
      "description": "The AngelHope Kidney Transplant Program is one of the longest-running, most exceptional programs of its kind in the country.",
      "longDescription": "Our areas of care. We offer a variety of transplant options to ensure that each patient receives the most appropriate care. Our areas of care include-    >>Adult kidney transplants- We are one of the country’s largest kidney transplant programs, and have exceptional outcome rates to match our high volumes. We are a leading referral center and continually treat patients with the most complex diseases.   >>Pediatric kidney transplants- Our Pediatric Kidney Transplant Program consistently leads the nation in both volume and outcomes. We have one of the highest 3-year graft and patient survival rates in the country, which far exceeds the national average.  >>Living donor kidney transplants- Living donor transplants tend to offer more immediate function and may last longer. We offer adult and pediatric transplants in one facility, meaning the living donor and the recipient receive care from the same expert team. This enhances recovery and makes the experience less stressful for adults and children alike.   >>Kidney exchange- Our Kidney Exchange Program increases the chances that you can find the right donor match. With kidney exchange, your donor gives a kidney to a compatible match, and you receive a kidney from a donor who is compatible with you.",
      "conditions": "Conditions we treat.  Common conditions we treat include-  >>Kidney disease (renal disease)- When your kidneys cannot filter your blood as effectively as they should.   >>Kidney failure (end-stage renal disease)- When your body can no longer filter toxins and remove waste from your blood.  >>Kidney failure is the primary reason that someone may need a kidney transplant. Some conditions that can lead to kidney failure include-   >>Chronic glomerulonephritis- Ongoing inflammation and scarring in the small filters in your kidneys, called glomeruli.   >>Diabetes- A condition that affects how your body processes carbohydrates, which can result in high blood sugar (glucose).   >>Polycystic kidney disease- A disorder that causes cysts to grow in your kidneys.     >>Uncontrolled high blood pressure (hypertension)- When the force of your blood against your artery walls is chronically too high.",
      "team": "Meet our team- Our team includes physicians and nurse practitioners who provide personalized care. We work closely with you before, during and after your transplant so you know exactly what to expect at each stage in your treatment journey."
    },
    {
      "id": 103,
      "name": "Liver Transplant",
      "review": 4.9,
      "price": 15050,
      "bannerImg": "https://i.ibb.co/QHVfWWG/livera-Banner.jpg",
      "image": "https://i.ibb.co/r7D2Bbv/liver.jpg",
      "description": "The AngelHope Liver Transplant Program is one of the most established, active programs of its kind in the country.",
      "longDescription": "Our areas of care.   >>Highlights of our Liver Transplant Program include:   >>Adult liver transplants: Our team has performed more than 6,000 liver transplants. We have achieved international recognition for our program and have developed many pioneering treatments that are now used worldwide.   >>Pediatric liver transplants: Our team at UCLA Mattel Children’s Hospital has performed more than 900 pediatric liver transplants. This high volume makes our Pediatric Liver Transplant Program one of the largest, most reputable programs of its kind in the world.   >>Living donor liver transplants: We are one of the only locations in the western United States where patients have access to living donor liver transplants. Since 1993, we have performed more than 100 of these procedures for adult and pediatric patients    >>Hepatobiliary surgery: If you have hepatitis C, advanced liver disease or another condition that requires a liver transplant, you may need specialized treatment while awaiting your transplant. Our hepatobiliary surgeons work hand-in-hand with transplant surgeons and the Dumont-UCLA Liver Cancer Center to evaluate and treat all patients with liver disease.",
      "conditions": "Conditions we treat.   >>If your liver stops working properly, you may need a liver transplant. There are several reasons why your liver may fail, including:   >>Autoimmune hepatitis: When your immune system attacks your liver, causing it to become inflamed.   >>Cirrhosis: When healthy liver tissue is replaced with scar tissue, often because of alcohol abuse or hepatitis.  >>Cholangiocarcinoma: Cancer that forms in your bile ducts, the tubes that carry fluid from your liver to your intestines.  >>End-stage liver disease (liver failure): Liver failure occurs when your liver stops performing its functions, such as storing sugar, breaking down saturated fat and ridding your body of drugs, alcohol and other toxins.   >>Hepatitis C: A liver infection caused by the hepatitis C virus.   >>Liver cancer: When cancerous cells begin in your liver.",
      "team": "Meet our team- Our team includes physicians and nurse practitioners who provide personalized care. We work closely with you before, during and after your transplant so you know exactly what to expect at each stage in your treatment journey."
    },
    {
      "id": 104,
      "name": "Pancreas Transplant",
      "review": 4.7,
      "price": 16050,
      "bannerImg": "https://i.ibb.co/7bnJ6sL/pancrias-Banner.jpg",
      "image": "https://i.ibb.co/ZmYgbbQ/pancrias.jpg",
      "description": "For more than 20 years, our specialists have been offering expert pancreas transplants for patients with diabetes and pancreatic disease.",
      "longDescription": "Our areas of care.   >>We provide a few types of pancreas transplants. Our areas of care include:   >>Pancreas transplants for diabetes: We offer pancreatic transplants for patients with certain types of diabetes. A pancreas transplant can allow patients with type 1 diabetes to stop depending on insulin, and live without the negative or dangerous side effects of diabetes. We have performed more than 250 pancreas transplants for diabetes.   >Auto islet cell transplant: Sometimes, patients with pancreatic disease still have functioning insulin- and enzyme-producing cells that aid with digestion and blood sugar regulation, called islets. We are one of the only centers in the world that offers islet cell transplants. With this surgery, your body can continue producing insulin after we remove the pancreas.   >>Kidney-pancreas transplants: Patients who have both diabetes and kidney failure may need a transplant for both their pancreas and kidney. Both organs come from the same donor, which lowers the risk that your body will reject either organ.   >>Pancreas after kidney transplant: We also perform pancreas transplants for patients who already have a transplanted kidney that is working well. Patients may pursue this option if they received a living donor kidney transplant and are waiting to receive a donor pancreas.",
      "conditions": "Conditions we treat.   >>The two most common reasons that patients need a pancreas transplant are diabetes and kidney failure.   >>In partnership with the UCLA Center for Pancreas Care, we treat a range of conditions, including:  >>Pancreatic cancer: When cancerous cells grow in the pancreas, the organ that aids digestion and regulates blood sugar.    >>Pancreatitis: Inflammation in your pancreas that causes intense stomach pain and tenderness.   >>Type 1 diabetes: A chronic condition where your pancreas does not produce insulin as it should.   >>Type 2 diabetes: When your body does not use insulin correctly, resulting in elevated blood sugar. ",
      "team": "Meet our team- Our team includes physicians and nurse practitioners who provide personalized care. We work closely with you before, during and after your transplant so you know exactly what to expect at each stage in your treatment journey."
    },
    {
      "id": 105,
      "name": "Pediatric Kidney Transplant",
      "review": 4.9,
      "price": 17550,
      "bannerImg": "https://i.ibb.co/LRLqSkx/kidny-Banner.jpg",
      "image": "https://i.ibb.co/L65G7zB/kidney-Ped.jpg",
      "description": "Our specialists are experts in pediatric kidney transplants, with exceptionally high survival rates in recent years.",
      "longDescription": "Our areas of care.   >>When your child needs an organ transplant, you want to find them the right match as quickly as possible. That’s our goal, too.   >>We offer options to help expand the donor pool and increase the likelihood that your child receives timely treatment. Some of our options include:   >>Immunogenetics for transplants: Our Immunogenetics Center is a World Health Organization reference laboratory for crossmatch testing and HLA typing. This means that we are experts at analyzing genes, antibodies and tissue so that we can help your child find an excellent donor match.   >>Incompatible donor transplants: At UCLA Health, we can sometimes perform transplants even when the donor and recipient are not a perfectly compatible pair. We are experts in a process called “desensitizing,” where we lower certain types of antibodies in the recipient’s blood. This means your child is more likely to accept the donor organ, broadening the donor pool even further.   >>Pediatric kidney exchange: We are one of the only centers in the nation that offers kidney exchange for children. Since 2008, our Kidney Exchange Program has allowed more children and adults to receive living donor transplants. We achieve this by matching living donors and recipients with other donor/recipient pairs who are a compatible match.",
      "conditions": "Conditions we treat.   >>We offer kidney transplants for children whose kidneys have stopped working, resulting in kidney failure. Some of the reasons for pediatric kidney failure can include:   >>>Birth defects.    >>>Birth defects that can affect the kidneys include:   >>>Ectopic kidneys: When the kidneys are in the wrong place.    >>>Horseshoe kidney: When both kidneys join and form a horseshoe shape.   >>>Kidney dysplasia: When a kidney functions improperly or not at all.   >>>Inherited kidney disease.    >>>In some cases, children may be born with rare forms of kidney disease, such as:    >>>Autosomal recessive polycystic kidney disease: When large cysts grow in the kidneys and cause severe illness.   >>>Multicystic dysplastic kidney (MCDK) disease: When the kidney does not develop properly, and cysts take over healthy tissue.",
      "team": "Meet our team- Our specialists are experts in clinical care as well as research. We consistently pave the way in establishing new treatments and techniques, and increasing access for children to receive liver transplants. Our team includes experts in liver transplant surgery as well as pediatric gastroenterology. "
    },
    {
      "id": 106,
      "name": "Pediatric Liver Transplant",
      "review": 4.8,
      "price": 16650,
      "bannerImg": "https://i.ibb.co/8DffXmC/liver-Banner-Ped.jpg",
      "image": "https://i.ibb.co/JBmGbHZ/liverPed.jpg",
      "description": "The AngelHope Pediatric Liver Transplant Program is one of the largest, most well-established programs of its kind in the world.",
      "longDescription": "Conditions we treat.    >>>Children are candidates for liver transplants if they have severe liver problems. Some reasons a child might need a transplant include:    >>>Alagille syndrome: A genetic disorder in which babies have fewer bile ducts — the tubes that carry fluid from the liver to the small intestine — than usual.    >>>Alpha-1 antitrypsin deficiency: A condition in which alpha-1 antitrypsin proteins, proteins that protect the lungs, are not the correct shape, increasing one’s risk for liver disease.    >>>Biliary atresia: A rare disease in the bile ducts and liver that occurs in newborns.    >>>Hemochromatosis: A hereditary condition that can cause too much iron in the body.    >>>Liver cancer: When cancerous cells form and spread in the liver.    >>>Viral hepatitis: An infection that leads to liver inflammation.",
      "conditions": "Treatments we offer.    >>>Thanks to our team’s commitment to research and innovation, we offer approaches that expand the available donor pool for your child. Some of these techniques include:    >>>Adult-to-child living donor transplants: With this option, adults can donate a part of their liver to a child recipient. The donor is usually a close family friend or relative.    >>>Split-liver allografts: With this procedure, we can split a deceased donor organ into two portions to give to two different children. This technique allows more children who need transplantations to receive them.     >>>Multi-organ transplants: We continue to research the best ways to perform multiple organ transplants in children, such as liver-heart transplants for children who also have heart conditions.",
      "team": "Meet our team- Our specialists are experts in clinical care as well as research. We consistently pave the way in establishing new treatments and techniques, and increasing access for children to receive liver transplants. Our team includes experts in liver transplant surgery as well as pediatric gastroenterology. "
    }
  ]